import { Servicio } from "./servicio";

export const SERVICIOS:Servicio[] =  [ 
    {    id : 1,
        modalidad: "guia de turismo",
        region: "Lima",
        plataforma: "zoom",
        usuario: "jack",
        name: "guia de macchu picchu",
        description: "visita guiada a la ciudadela ",
        init_date: "1-06-2021",
        end_date: "1-07-2021",
        price: 200 },
    {     id : 2,
        modalidad: "guia de turismo",
        region: "Lima",
        plataforma: "zoom",
        usuario: "jack",
        name: "guia de Lineas de Nazca",
        description: "visita guiada a las Lineas de Nazca ",
        init_date: "1-06-2021",
        end_date: "1-07-2021",
        price: 200},
    {     id : 3,
        modalidad: "guia de turismo",
        region: "Lima",
        plataforma: "zoom",
        usuario: "jack",
        name: "guia de Tarapoto",
        description: "visita guiada a la naturaleza ",
        init_date: "1-06-2021",
        end_date: "1-07-2021",
        price: 200}
   
  ];